name: Build LibreTime Tagger

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write
  actions: read

env:
  APP_NAME: "LibreTime Tagger"
  SCRIPT_FILE: "libretime_tagger.py"
  MAC_ICON: "icon.icns"
  WIN_ICON: "icon.ico"

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow mutagen
    
    - name: Build Windows executable
      run: |
        # Keep onefile for Windows (works fine)
        pyinstaller --name="${{ env.APP_NAME }}" --windowed --onefile --icon=${{ env.WIN_ICON }} --clean ${{ env.SCRIPT_FILE }}
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: LibreTime-Tagger-Windows
        path: dist/${{ env.APP_NAME }}.exe
    
    - name: Get release upload URL
      if: startsWith(github.ref, 'refs/tags/')
      id: get_release
      uses: actions/github-script@v6
      env:
        TAG_NAME: ${{ github.ref_name }}
      with:
        script: |
          const { data: release } = await github.rest.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: process.env.TAG_NAME
          });
          core.setOutput('upload_url', release.upload_url);
    
    - name: Upload Windows to release
      if: steps.get_release.outputs.upload_url
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./dist/${{ env.APP_NAME }}.exe
        asset_name: ${{ env.APP_NAME }}-Windows.exe
        asset_content_type: application/octet-stream

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow mutagen
    
    - name: Build macOS app (onedir mode)
      run: |
        # Use onedir mode for macOS app bundles (fixes the warning)
        pyinstaller --name="${{ env.APP_NAME }}" \
                   --windowed \
                   --onedir \          # ← CHANGED: onedir instead of onefile
                   --icon=${{ env.MAC_ICON }} \
                   --clean \
                   ${{ env.SCRIPT_FILE }}
    
    - name: Create DMG package from app bundle
      run: |
        brew install create-dmg
        create-dmg \
          --volname "${{ env.APP_NAME }}" \
          --volicon "${{ env.MAC_ICON }}" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon-size 100 \
          --icon "${{ env.APP_NAME }}.app" 175 180 \    # ← Now it's .app
          --hide-extension "${{ env.APP_NAME }}.app" \
          --app-drop-link 425 180 \
          "${{ env.APP_NAME }}-${GITHUB_REF_NAME}.dmg" \
          "dist/"
    
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LibreTime-Tagger-macOS
        path: |
          dist/${{ env.APP_NAME }}.app/    # ← Now it's a .app bundle
          ${{ env.APP_NAME }}-*.dmg
    
    - name: Get release upload URL
      if: startsWith(github.ref, 'refs/tags/')
      id: get_release
      uses: actions/github-script@v6
      env:
        TAG_NAME: ${{ github.ref_name }}
      with:
        script: |
          const { data: release } = await github.rest.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: process.env.TAG_NAME
          });
          core.setOutput('upload_url', release.upload_url);
    
    - name: Upload macOS app bundle to release
      if: steps.get_release.outputs.upload_url
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./dist/${{ env.APP_NAME }}.app
        asset_name: ${{ env.APP_NAME }}-macOS.app.zip
        asset_content_type: application/zip
    
    - name: Upload macOS DMG to release
      if: steps.get_release.outputs.upload_url
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./${{ env.APP_NAME }}-${GITHUB_REF_NAME}.dmg
        asset_name: ${{ env.APP_NAME }}-macOS.dmg
        asset_content_type: application/octet-stream
